export const ALL_CHECKED = 'ALL_CHECKED'
export const CHECKED = 'CHECKED'
export const TAB_CHEAP = 'TAB_CHEAP'
export const TAB_FAST = 'TAB_FAST'
export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const GET_TICKET = 'GET_TICKET'
export const ERROR = 'ERROR'
export const RENDER_TICKETS = 'RENDER_TICKETS'
